image: nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04-rc

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  FF_USE_LEGACY_GIT_CLEAN_STRATEGY: 1

before_script:
  - apt update && apt install -y cmake
  - mkdir ${CI_PROJECT_DIR}/build
  - cd ${CI_PROJECT_DIR}/build
  - cmake -DCMAKE_BUILD_TYPE=Release -DSM=70 -DNCCL_INCLUDE_DIR=/usr/local/cuda-11.0/targets/x86_64-linux/include -DNCCL_LIBRARIES=/usr/local/cuda-11.0/targets/x86_64-linux/lib ..
  - make -j

unit_tests:
  tags:
    - hugectr
  script:
    - cd ${CI_PROJECT_DIR}/build/bin
    - ./session_test
    - ./checker_test
    - ./data_parser_test
    - ./data_reader_test
    - ./device_map_test
    - ./embedding_test
    - ./heap_test
    - ./layers_test
    - ./loss_test
    - ./optimizer_test
    - ./parser_test
    - ./regularizers_test